knpu_oauth2_client:
    clients:
        keycloak:
            type: keycloak
            client_id: '%env(OAUTH_CLIENT_ID)%'
            client_secret: '%env(OAUTH_CLIENT_SECRET)%'
            redirect_route: sso_check
            redirect_params: { }
            auth_server_url: '%env(OAUTH_APP_URL)%'
            realm: '%env(OAUTH_REALM)%'
            use_state: false
            version: '20.0.2'
