twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    globals:
        app_title: '%app.name%'
        app_subtitle: '%app.longName%'
        app_version: '%app.version%'
when@test:
    twig:
        strict_variables: true
